### ISSUE TITLE
firebase use flask route get "ECONNRESET" ,The restful api never response until 60s timeout

### ISSUE THREAD

**Issue by xactester** [firebase/firebase-functions-python#159]
```
@app.post("/api/test")
def stuff():
    abc = flask.request.get_data()
    # abc= flask.request.get_json();
    print("Jsondata:", abc)
    # name = flask.request.args.get('name')
    # print("name:", name)
    data = {'Message': 'Hello World'}
    return jsonify(data), 200
```
```
@https_fn.on_request()
def httpsflaskexample(req: https_fn.Request) -> https_fn.Response:
    with app.request_context(req.environ):
        return app.full_dispatch_request()
```
A sample like [firebase_documents](https://firebase.google.com/docs/functions/http-events?gen=2nd&hl=zh-cn#python-preview_2)
If i remove request.get_data(), It will be ok.

**Comment by fzrcyc** [comment]
I'm having the same problem when i call  flask.request.get_data() in post
this is the  traceback:
  Traceback (most recent call last):
>    File "D:\MyDemo\functions\venv\lib\site-packages\flask\app.py", line 1508, in finalize_request
>      response = self.process_response(response)
>    File "D:\MyDemo\functions\venv\lib\site-packages\flask\app.py", line 2002, in process_response
>      response = self.ensure_sync(func)(response)
>    File "D:\MyDemo\functions\venv\lib\site-packages\functions_framework\__init__.py", line 302, in read_request    
>      flask.request.get_data()
>    File "D:\MyDemo\functions\venv\lib\site-packages\werkzeug\wrappers\request.py", line 420, in get_data
>      rv = self.stream.read()
>    File "D:\MyDemo\functions\venv\lib\site-packages\werkzeug\wsgi.py", line 577, in readall
>      data = self.read(1024 * 64)
>    File "D:\MyDemo\functions\venv\lib\site-packages\werkzeug\wsgi.py", line 562, in readinto
>      self.on_disconnect()

stuck in read and then timeout. if post with no body, it's fine.

**Comment by fzrcyc** [comment]
I found a temporary solution.

`@https_fn.on_request()
def httpsflaskexample(req: https_fn.Request) -> https_fn.Response:
    with app.request_context(req.environ):
        g.request = req
        return app.full_dispatch_request()`

then use g.request in post function

`@app.post("/api/test")
def stuff():
    abc = g.request.get_data()
    # abc= flask.request.get_json();
    print("Jsondata:", abc)
    # name = flask.request.args.get('name')
    # print("name:", name)
    data = {'Message': 'Hello World'}
    return jsonify(data), 200`

**Comment by bigminions** [comment]
> Same issue with request.json which calls get_json @fzrcyc work around worked but very hacky lol

Same, if I add get_json, it is timeout. Remove that, return ok
@test_bp.get('/hello')
def hello():
    data = request.get_json()
    return "hello world"

**Comment by nvzoll** [comment]
@ravpiotrowski use a cloud run service with Flask, python CFs spawn one per function anyway

**Comment by ravpiotrowski** [comment]
yep, too many problems using python CFs, thanks @nvzoll

**Comment by HM-Cloudamai** [comment]
When running the code, the post request stops after request.get_data() is called. If I remove it, it returns back normally.

Tested with the example @exaby73 provided above.

**Comment by HM-Cloudamai** [comment]
Found something interesting, I used Windows WSL to run my cloud functions and all of a sudden it is working. Looks like this is some issue with Windows based machines (Powershell)?

**Comment by nvzoll** [comment]
Yes, it might be, I discovered the issue running the emulator on Windows locally as well

**Comment by hunghng** [comment]
Facing the same issue. I'm giving up

**Comment by cabljac** [comment]
Hi all, re-escalating this with the team. We will provide updates when available.

**Comment by IzaakGough** [comment]
Closing as unable to reproduce. Tested using the above example by @exaby73; works correctly on both the emulator and a deployment. This issue seems to be fixed now. We can re-open if the issue persists.
