### ISSUE TITLE
ModuleNotFoundError: No module named 'util'

### ISSUE THREAD

**Issue by lubaspc** [firebase/firebase-functions-python#162]
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
 File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/functions_framework/__init__.py", line 174, in view_func
    function(event)
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/firebase_functions/alerts/crashlytics_fn.py", line 295, in crashlytics_decorator_wrapped
from firebase_functions.private._alerts_fn import crashlytics_event_from_ce
 File "/layers/google.python.pip/pip/lib/python3.11/site-packages/firebase_functions/private/_alerts_fn.py", line 19, in <module>
    import util as _util
ModuleNotFoundError: No module named 'util'

**Comment by lubaspc** [comment]
change 
import util as _util
for
import firebase_functions.private.util as _util

**Comment by exaby73** [comment]
Hey. Could you provide me with some example code and also which version of `firebase_functions` you're using?

**Comment by lubaspc** [comment]
Estoy usando la version 0.2.0

archivo _alerts_fn.py


import typing as _typing
import cloudevents.http as _ce
import util as _util
from firebase_functions.alerts import FirebaseAlertData

from functions_framework import logging as _logging

cambiar por 

import firebase_functions.private.util as _util

**Comment by LeslieLeung** [comment]
Hi, I made a pr #168 to fix this, but I don't know who to assign to. @exaby73 Can you have a look?

**Comment by LeslieLeung** [comment]
FYI, here is a code example.

```python

import firebase_functions.alerts.crashlytics_fn as crashlytics_fn
from firebase_admin import initialize_app
import requests

initialize_app()


@crashlytics_fn.on_velocity_alert_published()
def on_velocity_alert_published(alert):
    alert_handle(alert)

def alert_handle(alert):
    # some curl code with requests
```

And the error log:

```
[2024-01-08 05:51:47,013] ERROR in app: Exception on / [POST]
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app response = self.full_dispatch_request()
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
rv = self.dispatch_request()
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/functions_framework/__init__.py", line 178, in view_func
function(event)
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/firebase_functions/alerts/crashlytics_fn.py", line 295, in crashlytics_decorator_wrapped
from firebase_functions.private._alerts_fn import crashlytics_event_from_ce
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/firebase_functions/private/_alerts_fn.py", line 19, in <module>
import util as _util
ModuleNotFoundError: No module named 'util'
```
