### ISSUE TITLE
KeyError: `authtype`

### ISSUE THREAD

**Issue by DominicOrga** [firebase/firebase-functions-python#197]
My Python Firestore event trigger has suddenly broke down and is throwing the following error:
```
2024-04-17 13:46:52.010 HKT
Traceback (most recent call last):   File "/layers/google.python.pip/pip/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app     response = self.full_dispatch_request()
2024-04-17 13:46:52.010 HKT
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-17 13:46:52.010 HKT
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
2024-04-17 13:46:52.010 HKT
    rv = self.handle_user_exception(e)
2024-04-17 13:46:52.010 HKT
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-17 13:46:52.010 HKT
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
2024-04-17 13:46:52.010 HKT
    rv = self.dispatch_request()
2024-04-17 13:46:52.010 HKT
         ^^^^^^^^^^^^^^^^^^^^^^^
2024-04-17 13:46:52.010 HKT
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
2024-04-17 13:46:52.010 HKT
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
2024-04-17 13:46:52.010 HKT
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-17 13:46:52.010 HKT
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/functions_framework/__init__.py", line 178, in view_func
2024-04-17 13:46:52.010 HKT
    function(event)
2024-04-17 13:46:52.010 HKT
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/firebase_functions/firestore_fn.py", line 246, in on_document_written_wrapped
2024-04-17 13:46:52.010 HKT
    return _firestore_endpoint_handler(
2024-04-17 13:46:52.010 HKT
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-17 13:46:52.010 HKT
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/firebase_functions/firestore_fn.py", line 137, in _firestore_endpoint_handler
2024-04-17 13:46:52.010 HKT
    event_auth_type = event_attributes["authtype"]
2024-04-17 13:46:52.010 HKT
                      ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
2024-04-17 13:46:53.037 HKT
KeyError: 'authtype'
```

I've tested this on both firebase_function `0.3.0` and `0.4.0`.

**Comment by exaby73** [comment]
Closing in favor of https://github.com/firebase/firebase-functions-python/issues/194. I'll have a fix out soon
