### ISSUE TITLE
test_lab_fn: Error when triggered by unlabeled test

### ISSUE THREAD

**Issue by kevinthecheung** [firebase/firebase-functions-python#64]
When an unlabeled test triggers `on_test_matrix_completed`, it throws the following:

```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/functions_framework/__init__.py", line 174, in view_func
    function(event)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/firebase_functions/test_lab_fn.py", line 273, in on_test_matrix_completed_wrapped
    return _event_handler(func, raw)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/firebase_functions/test_lab_fn.py", line 225, in _event_handler
    details=event_data["clientInfo"]["details"],
KeyError: 'details'
```

**Comment by Salakar** [comment]
It seems that 'details' in client info can sometimes be undefined, I based the python code off the JS Functions SDK code - the types there should probably also be updated since there it indicates that details is [always defined](https://github.com/firebase/firebase-functions/blob/master/src/v2/providers/testLab.ts#L115-L116) but it's not always available as shown by this issue). I've pushed a fix for Python on PR #80 

cc @taeold
