### ISSUE TITLE
Trying to install functions python runtime on Windows resuslts in OSError

### ISSUE THREAD

**Issue by muddi900** [firebase/firebase-functions-python#99]

**Comment by Jackilion** [comment]
I ran into the same problem. I used python 3.9, but the firebase package requires python >3.10. Upgrading and updating the path variables solved the issue.

If it still doesn't work:
The problem comes from the "python.js" file, located under
``` AppData\Roaming\npm\node_modules\firebase-tools\lib\functions ```

Line 29 onwards:

```
    const install = await (0, prompt_1.promptOnce)({
        name: "install",
        type: "confirm",
        message: "Do you want to install dependencies now?",
        default: true,
    });
    if (install) {
        const upgradeProcess = (0, python_2.runWithVirtualEnv)(["pip3", "install", "--upgrade", "pip"], config.path(setup.functions.source), {}, { stdio: ["inherit", "inherit", "inherit"] });
        await new Promise((resolve, reject) => {
            upgradeProcess.on("exit", resolve);
            upgradeProcess.on("error", reject);
        });
        const installProcess = (0, python_2.runWithVirtualEnv)([(0, python_1.getPythonBinary)(python_1.LATEST_VERSION), "-m", "pip", "install", "-r", "requirements.txt"], config.path(setup.functions.source), {}, { stdio: ["inherit", "inherit", "inherit"] });
        await new Promise((resolve, reject) => {
            installProcess.on("exit", resolve);
            installProcess.on("error", reject);
        });
    }
}
```
It seems that after you hit "yes" to installing dependencies, the script tries to upgrade pip, and then install the packages specified under "requirements.txt". It is the upgrade pip command that fails.

If you simply hit "no", the setup completes. You can then go ahead and pip install requirements.txt on your own. (This is how I found out my python version was too old - it gave me a more helpful error message when I did it manually. After upgrading python I tried to go through the setup again and this time it completed.)

**Comment by muddi900** [comment]
My environment is 3.10 on Windows.

Thank you

**Comment by B2Gdevs** [comment]
Same issue.  I have tried numerous times, here are some logs from the `firebase-debug.log` file.
```
[info] i  Skipping write of functions/requirements.txt 
[info] i  Skipping write of functions/.gitignore 
[info] i  Skipping write of functions/main.py 
[debug] [2023-06-15T02:14:56.546Z] Running command with virtualenv: command="C:\Users\stacho\Documents\custominstallations\action_items_ai\functions\venv\Scripts\activate.bat", args=["","&&","pip3","install","--upgrade","pip"]
[debug] [2023-06-15T02:14:57.427Z] Error: spawn "C:\Users\stacho\Documents\custominstallations\action_items_ai\functions\venv\Scripts\activate.bat" ENOENT
    at notFoundError (C:\Users\stacho\AppData\Roaming\nvm\v18.13.0\node_modules\firebase-tools\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\stacho\AppData\Roaming\nvm\v18.13.0\node_modules\firebase-tools\node_modules\cross-spawn\lib\enoent.js:40:16)
    at cp.emit (C:\Users\stacho\AppData\Roaming\nvm\v18.13.0\node_modules\firebase-tools\node_modules\cross-spawn\lib\enoent.js:27:25)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[error] 
[error] Error: An unexpected error has occurred.
```

^^ the above fails just to activate the environment

Then when I actually activate the environment by just doing `source venv/Scripts/activate`

I get the below

```
[info] i  Skipping write of functions/requirements.txt 
[info] i  Skipping write of functions/.gitignore 
[info] i  Skipping write of functions/main.py 
[debug] [2023-06-15T02:19:23.096Z] Error: spawn python.exe ENOENT
    at notFoundError (C:\Users\stacho\AppData\Roaming\nvm\v18.13.0\node_modules\firebase-tools\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\stacho\AppData\Roaming\nvm\v18.13.0\node_modules\firebase-tools\node_modules\cross-spawn\lib\enoent.js:40:16)
    at cp.emit (C:\Users\stacho\AppData\Roaming\nvm\v18.13.0\node_modules\firebase-tools\node_modules\cross-spawn\lib\enoent.js:27:25)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[error] 
[error] Error: An unexpected error has occurred.
```

Here is some other info, hopefully it helps

```
[debug] [2023-06-15T02:19:12.209Z] ----------------------------------------------------------------------
[debug] [2023-06-15T02:19:12.210Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2023-06-15T02:19:12.211Z] CLI Version:   12.3.1
[debug] [2023-06-15T02:19:12.211Z] Platform:      win32
[debug] [2023-06-15T02:19:12.211Z] Node Version:  v18.13.0
[debug] [2023-06-15T02:19:12.212Z] Time:          Wed Jun 14 2023 21:19:12 GMT-0500 (Central Daylight Time)
[debug] [2023-06-15T02:19:12.212Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-06-15T02:19:12.269Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
```

**Comment by William-LP** [comment]
A fresh install of python fixed it for me.

**Comment by hmalik144** [comment]
1. open powershel as admin
2. Set-ExecutionPolicy RemoteSigned
3. go back to terminal in project
4. firebase init -> select functions -> language = python -> (go through until Do you want to install dependencies now?) 
5. Do you want to install dependencies now? Yes

activiate.bat should now be in /functions/venv/Scripts

**Comment by jelling** [comment]
Same `spawn "C:\src\maiker\functions\venv\Scripts\activate.bat" ENOENT` issue. Fix was to reinit the Firebase project. I suspect this worked because Firebase then created the `venv` directory as it wanted. 

Odd part was that I had a working environment as of a week or two ago and had previously deployed the functions.

**Comment by sieutruc** [comment]
I got the same error , any solution for that?

**Comment by sieutruc** [comment]
@Anquuni a workaround is to reinstall the Python that fixed for me.

**Comment by maximalniq** [comment]
Instal python >3.10 , and restart system

**Comment by ivanandresdiaz** [comment]
I faced that problem and the solution was kind of easy. I installed the request pip version and retry with firebase init. 

I made a video on youtube may help you

https://www.youtube.com/watch?v=q_sayYt50oM

**Comment by paulo101977** [comment]
I manually installed the packages using Python on my machine, instead of the binaries that Firebase downloads:

``` python -m pip install -r requirements.txt -t ./venv/Lib/site-packages/```

This command must be run within the directory where the requirements.txt
